# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:16:40+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    EscerCertificatePostRequest,
    EscerCertificatePostResponse,
    EscerCertificatePostResponse1,
    EscerCertificatePostResponse2,
    EscerCertificatePostResponse3,
    EscerCertificatePostResponse4,
    EscerCertificatePostResponse5,
    EscerCertificatePostResponse6,
    SkcerCertificatePostRequest,
    SkcerCertificatePostResponse,
    SkcerCertificatePostResponse1,
    SkcerCertificatePostResponse2,
    SkcerCertificatePostResponse3,
    SkcerCertificatePostResponse4,
    SkcerCertificatePostResponse5,
    SkcerCertificatePostResponse6,
)

app = MCPProxy(
    description='NSDC (https://www.nsdcindia.org) promotes skill development by catalyzing creation of large, quality and for-profit vocational institutions. Skill certificates provided under various NSDC programmes are made available to citizens in their DigiLocker accounts.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='National Skill Development Corporation (NSDC)',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/nsdcindia/v3'}],
)


@app.post(
    '/escer/certificate',
    description=""" API to verify Executive Skill Enhancement Certificate. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def escer(body: EscerCertificatePostRequest = None):
    """
    Executive Skill Enhancement Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/skcer/certificate',
    description=""" API to verify Skill Certificate. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def skcer(body: SkcerCertificatePostRequest = None):
    """
    Skill Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
